highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 20
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "<!--more-->"

url: https://quantekk.github.io # Required: replace this with your domain
name: 奇怪的知识  # Required: will be displayed on every page's header
title: 奇怪的知识  # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - 一本正经、胡说八道
  - :-)
description: "quantek的个人记录" # Required

disqus:
  comments: false # Global toggle on/off disqus comment
  shortname: quantekk # Required if you use disqus. Repalce with your disqus shortname here

google_analytics:
  id: "G-W98K5W1MXK" # Required if you use google analytics. Replace with your tracking id here

#collections: # Define post series here
  #生命的实验室:
  #  output: true
  #demo_series_2:
  #  output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"